version: '3.8'

services:
  backend:
    build:
      context: ./comment-backend
    container_name: comment_backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://comment_db_a79l_user:88t3bcjfLUCILZZCdPuCsQ3rs68BfTzu@dpg-d1l9lqidbo4c739odsog-a.singapore-postgres.render.com/comment_db_a79l?sslmode=require
      JWT_SECRET: 88t3bcjfLUCILZZCdPuCsQ3rs68BfTzu
    volumes:
      - ./comment-backend:/app
    command: npm run start:dev
    dns:
      - 8.8.8.8
      - 8.8.4.4
